### PR TITLE
qvm backup

### PR DESCRIPTION
**Pull request by neoniobium**
I have added completion for the `qvm-backup`. This should include all options. Please review.

Note:
- I have not included compression filters other then `gzip`.
- Path completion is not working for target qubes other then `dom0`.

### CODE REVIEW

**Comment by jamke** [comment]
First implementation of "complete completion" that is not done by me, good job!

The code, though, has some issues and a room for improvement:

1. I would use standalone arguments counter to prevent providing flags or even values of previous flag in case 1+ standalone argument was provided. It is not correct call according to `man`.
2. In case there were no standalone args before - provide backup_location (clever way would be also to check `--dest-vm` value and for 'dom0' or no value provide file dir completion, otherwise provide nothing).
3. If there is 1+ standalone arg - provide qubes names.
4. Dest vm should be completed by only running qubes, otherwise it does not work, is it right?
5. Arguments -v/-q/-h and long versions should not be provided explicitly (to keep DRY). It is automatically done according to ${COMPLETION_ALL_BASIC}.


You can choose the way forward:
- try to fix all these issues and improvements, or 
- wait for me, when I have time to accept your PR and fix all these myself. I was planning to do `qvm-backup` in a week or something.

**Comment by neoniobium** [comment]
Addressed most of the issues. For the remaining see TODOs. 

Additionally I have done some cleaning and I have made it a draft.

**Comment by jamke** [comment]
Well done. I will be able to approve the commit in about a week, hope it is OK.

About code, a couple minor issues:
* extra space in `${flags_require_one}` at the end
* I believe `${QB_prev_flag}` is still processed even when there are standalone arguments, that should not be the case according to the `man`, even if it actually works that way. E.g. `qbm-blackup 'mypath' qube1 qube2 --dest<TAB><TAB>` should complete nothing according to `man`, right?

**Comment by neoniobium** [comment]
> Well done. I will be able to approve the commit in about a week, hope it is OK.

Fine with me.

**Comment by neoniobium** [comment]
> I believe ${QB_prev_flag} is still processed even when there are standalone arguments, that should not be the case according to the man, even if it actually works that way. E.g. qbm-blackup 'mypath' qube1 qube2 --dest<TAB><TAB> should complete nothing according to man, right?

Indeed. I fix this later.

**Comment by jamke** [comment]
Probably, that is the current list of compression filters: 
`KNOWN_COMPRESSION_FILTERS = ('gzip', 'bzip2', 'xz')`

Source: https://github.com/QubesOS/qubes-core-admin-client/blob/ba9b24db90c1b09826b6fcff61f98941565a2824/qubesadmin/backup/restore.py#L68

**Comment by jamke** [comment]
OK, sorry for taking so long for migration my dev environment. Now I am ready to accept you PR and add minor fixes if needed. 
The PR is currently a draft, should I consider it to be ready for review and proceed?

**Comment by jamke** [comment]
Accepted, thank you. I will make minor improvements soon.

**Comment by jamke** [comment]
I made some improvements:
* ffef444 - style changes and fix of point 1 from https://github.com/jamke/qubes-completion/pull/5#issuecomment-1619006993
* 372df86 - deals with corner case of `--dest-vm` (and `-d` that was forgotten!) being set to `dom0`.

Maybe you should check it works as you expect, I hope I did not break anything.

**Comment by neoniobium** [comment]
Looks good to me and works as expected.

**Pull request merged**
