### PR TITLE
[qubesctl] added new options for Q4.2

### PR DESCRIPTION
**Pull request by neoniobium**

### CODE REVIEW

**Comment by jamke** [comment]
Thank you. All 3 recent PR request of yours are great.
The only problem that currently both releases R4.1 and R4.2 are supported, so I am not so sure what should be done to allow people of both releases use the project. Do you have any strong opinion what should we do? Just drop R4.1? 
Maybe I should add some additional configuration option to toggle this.

**Comment by neoniobium** [comment]
At this stage I think there is rather  shall number of people using this project. Those are likely command line heavy users, which I would suppose have updated already. Furthermore those who are still on `Q4.1` can use a earlier releases. You could just mention it in the `Readme`.

**Comment by neoniobium** [comment]
Of cause  a configuration --or an automation-- for the distinction between the releases would be premium but I think that it will be not be worth the afford.

**Comment by jamke** [comment]
OK, for now we will target to R4.2 mostly.

**Pull request merged**
