### PR TITLE
Add testing dependencies (as Git submodules)

### LINKED ISSUE #9: BATS tools could be included to make testing setup easier
## Overview

- Currently, testing currently depends on three tools provided by the BATS framework ([docs](https://github.com/jamke/qubes-completion/tree/v1.0.1#tests)):
  - bats-assert ([`CC0-1.0`](https://github.com/bats-core/bats-assert/blob/v2.1.0/LICENSE))
  - bats-file ([`CC0-1.0`](https://github.com/bats-core/bats-file/blob/v0.3.0/LICENSE))
  - bats-support ([`CC0-1.0`](https://github.com/bats-core/bats-support/blob/v0.3.0/LICENSE))
- Those need to be present in a specific path of the project before the existing test suite can be executed (`test/test_helper/bats-*`).
- Given their license, they could be included in the project

## Why

- Remove the need for would-be contributors to fetch and add them themselves
- Open the possibility of running the test suite in a GitHub Action (I'll open a separate issue to discuss that)

### Git submodules

**Pros**: Adding the three BATS repositories as git _submodules_ makes it easier to keep track of which versions of the tools are currently in use, and eventually to update them.
**Cons**: However, it requires being aware of submodules when pulling the repository. (Mitigation: a note can be added to the **Tests** section of the documentation.) 

### Copies

A simple copy of the BATS tools can also be included with the project.

**Pros**: Simple. Those become part of the project like any other file, and no special setup is needed before tests can be run.
**Cons**: It is less obvious which version is used (which may or not matter).

### PR DESCRIPTION
**Pull request by gonzalo-bulnes**
## Overview

Includes the BATS dependencies in the repository for convenience. (And to make it easier for new contributors to run the test suite.)

This PR implements the recommendations from the BATS docs: https://bats-core.readthedocs.io/en/stable/tutorial.html#quick-installation

Fixes #9 

## Usage

See README updates :slightly_smiling_face:

### CODE REVIEW

**Comment by jamke** [comment]
Thanks for well-made PR and issues!
About test suite: I am using it a bit differently. I installed these repos using clone to the recommended directory:
```
test/test_helper/bats-assert
test/test_helper/bats-file
test/test_helper/bats-support
```
and making them submodules should be a way to go.

But about `bats` repo I acted differently, I simply installed it from fedora repos (available in Qubes OS, too):
`sudo dnf install bats`
because I trust repos a bit more than github projects and installation makes it work making any required magic inside the system path and etc. Also bats is the biggest package of those four.

So, the question is: should we clone `bats` repo (as submodule) or recommend using it as a package from more reliable source?

Pros of github-version:  
* consistency of testing dependencies,
* updated faster, probably,
* maybe preferable for github-actions integration?

Cons:
* less reliable, bleeding edge and not reviewed by additional package repo maintainer,
* will be duplicated if used in several project.

**Comment by gonzalo-bulnes** [comment]
> But about bats repo I acted differently, I simply installed it from fedora repos (available in Qubes OS, too) […]

So did I initially, indeed. (Debian 11/Qubes OS)

It's once I added the other BATS tools as submodules that I thought I might as well add `bats` too.

> So, the question is: should we clone bats repo (as submodule) or recommend using it as a package from more reliable source?

👍 Yes. I haven't formed any strong preference myself at this point, I think both are valid options.

Regarding the pros/cons that you've listed:

> maybe preferable for github-actions integration?

I'd say yes, in that everything that's needed to run the test suite is available in the repo itself.

> updated faster, probably
> less reliable, bleeding edge […]

Can be, but doesn't have to be. Each submodule is committed in the repo at a specific point in the log of the remote repo. That is, the submodules are frozen, and the same versions will always be downloaded (`git submodule status`) until they are explicitly updated. Nothing prevents using a specific tag to get a specific version. Git submodules are very much a way of _vendoring_ dependencies, and provide the corresponding stability guarantees. (As stable as the remote repositories, that is… sure enough git tags can be moved around!)

_Maybe a controversial viewpoint: I don't see the need to update those submodules until actually needed to run the tests. "If they've got all that's needed, they've got all that's needed 🤷‍♀️" YMMV!_

> […] not reviewed by additional package repo maintainer

Packagers would certainly at least catch mistakes that prevent the tool from doing its primary job; I wouldn't assume much more than that personally.

Other that those nuances, I see the same pros/cons. 👍

Does any of this help you tilt the balance one way or another?

**Comment by jamke** [comment]
> Can be, but doesn't have to be. Each submodule is committed in the repo at a specific point in the log of the remote repo. That is, the submodules are frozen, and the same versions will always be downloaded (`git submodule status`) until they are explicitly updated. Nothing prevents using a specific tag to get a specific version. Git submodules are very much a way of _vendoring_ dependencies, and provide the corresponding stability guarantees. (As stable as the remote repositories, that is… sure enough git tags can be moved around!)

Good point, we defintely can keep this submodules frozen for avoiding any back-doors coming from upstream if everything works for us and update only in case something security-related changes upstream.

Another point is that adding repo as a submodule does not mean that we should not use original bats package for ourselves, does it. One can keep both package and luxury of calling `bats` at any directory and having github bats as an alternative.

So, adding `bats` is submodules is probably OK, too.

**Comment by jamke** [comment]
One thing that I notice about this change: the recommending way to locate `bats` repo is different to what you provide in commit. Maybe it is OK to put `bats` repo inside test_helper dir, too, but we probably should follow the docs. What do you think?

**Comment by gonzalo-bulnes** [comment]
> Another point is that adding repo as a submodule does not mean that we should not use original bats package for ourselves, does it. One can keep both package and luxury of calling bats at any directory and having github bats as an alternative

Absolutely!

And this reminds me that I wanted to add to the cons list:

- the path to call `bats` from the submodule by default is less nice than simply running `bats` from `$PATH`. (Nothing prevents from adding it to the `$PATH`, but as you say, it's extra steps.)

**Comment by gonzalo-bulnes** [comment]
> One thing that I notice about this change: the recommending way to locate bats repo is different to what you provide in commit.

Oh, you are right! That's my mistake, following the BATS docs seems like the way to go indeed!

I can fix that, and adjust the README accordingly 👍

**Comment by jamke** [comment]
Accepted. Bats-core relocated according to docs and `cd tests` change to `cd test` (probably typo).

**Pull request merged**
