### PR TITLE
[qvm-firewall] added completion for comment field

### PR DESCRIPTION
**Pull request by neoniobium**

### CODE REVIEW

**Comment by jamke** [comment]
Thank you, is it a R4.2-only field?

**Comment by neoniobium** [comment]
No this is `Q4. 1` too.

**Comment by jamke** [comment]
You are right, I checked on R4.1 and it works. But `man qvm-firewall`, nor `qvm-firewall --help` tells nothing about it, right?
So, we found an issue in these docs.

**Comment by neoniobium** [comment]
Yes, this is an issues with the docs.

**Comment by jamke** [comment]
> Yes, this is an issues with the docs.

Reported it to the Qubes OS. 
https://github.com/QubesOS/qubes-issues/issues/8879

**Pull request merged**
